Fix/error-parse
devtomio/sapphire-plugin-botlist pull request #60
Opened 2022-12-29 02:35 UTC by kaname-png

chore: bump deps

2023-01-22 21:29 UTC, vladfrangu requested changes

2023-01-22 21:29 UTC, vladfrangu commented on src/lib/Post.ts
> +				if (!errorMessage) errorMessage = await error.text().catch(() => null);
This won't work as the body would be consumed already

2023-01-23 01:11 UTC, kaname-png commented on src/lib/Post.ts
> +				if (!errorMessage) errorMessage = await error.text().catch(() => null);
How should i put it?

2023-01-25 14:35 UTC, devtomio commented on src/lib/Post.ts
> +			}
```suggestion
			if (err instanceof QueryError) {
				const error = err.response.clone();
				let errorMessage = await error.text();

				try {
					errorMessage = JSON.parse(errorMessage);
				} catch {}

				this.botList.emit('postStatsError', errorMessage ?? 'Unknown error.');
			}
```

2023-01-26 09:47 UTC, merged